platform :ios, '10.0'

target 'SFBaseKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SFBaseKit', :path => '../SFBaseKit'

  target 'SFBaseKitDemoTests' do
    inherit! :search_paths
  end

end
